name: bmi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.2.0

  percent_indicator: ^4.2.1
  provider: ^6.0.3
  hive: ^2.2.3
  hive_flutter:
  path_provider:
  flutter_native_timezone: ^2.0.0
  #Show notifications
  flutter_local_notifications: ^9.9.1
  #listen for notifications
  rxdart: ^0.27.5
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  hive_generator:

  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1

  flutter_lints: ^1.0.0
  
flutter_native_splash:
  color: "#0A0E21"
  image: assets/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png
    

flutter:

  uses-material-design: true
